apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-dev-branch-deploy-cluster
  region: ap-northeast-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
