apiVersion: v1
kind: Service

metadata:
  name: k8s-lb

spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: sample-app
